all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
- - 32
- - 33
- - 34
- - 35
- - 36
- - 37
- - 38
- - 39
- - 40
- - 41
- - 42
- - 43
- - 44
- - 45
- - 46
- - 47
- - 48
- - 49
- - 50
- - 51
- - 52
- - 53
- - 54
- - 55
- - 56
all_joints_names:
- tailtip
- tailbase
- anal
- genital
- hip
- sternumtail
- sternumhead
- neck
- snout
- lcheek
- rcheek
- lhip
- rhip
- lshoulder
- rshoulder
- lankle
- lhpaw
- lhpd1b
- lhpd1t
- lhpd2b
- lhpd2t
- lhpd3b
- lhpd3t
- lhpd4b
- lhpd4t
- lhpd5b
- lhpd5t
- lfpaw
- lfpd1b
- lfpd1t
- lfpd2b
- lfpd2t
- lfpd3b
- lfpd3t
- lfpd4b
- lfpd4t
- rankle
- rhpaw
- rhpd1b
- rhpd1t
- rhpd2b
- rhpd2t
- rhpd3b
- rhpd3t
- rhpd4b
- rhpd4t
- rhpd5b
- rhpd5t
- rfpaw
- rfpd1b
- rfpd1t
- rfpd2b
- rfpd2t
- rfpd3b
- rfpd3t
- rfpd4b
- rfpd4t
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_arcteryx500Nov4\arcteryx500_alex100shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 1.0
init_weights: C:\Users\alexz\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_arcteryx500Nov4\Documentation_data-arcteryx500_100shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 230000
- - 0.002
  - 430000
net_type: resnet_50
num_joints: 57
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: D:/DLC/arcteryx500-alex-2023-11-04
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
